#!/usr/bin/python

import sys

if len(sys.argv) < 2:
    print "usage: <sequence_stream> |", sys.argv[0], " <header>"
    exit()

header = sys.argv[1]

print ">" + header

fasta = sys.stdin.read(80)

while fasta != "":
    sys.stdout.write(fasta + '\n')
    fasta = sys.stdin.read(80).strip()

